# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTest():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_test(self):
    # Test name: test
    # Step # | name | target | value | comment
    # 1 | open | https://stories.duolingo.com/?referrer=web_tab |  | 
    self.driver.get("https://stories.duolingo.com/?referrer=web_tab")
    # 2 | setWindowSize | 1280x773 |  | 
    self.driver.set_window_size(1280, 773)
    # 3 | click | css=.set:nth-child(2) > .story:nth-child(3) .story-cover-illustration-image |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".set:nth-child(2) > .story:nth-child(3) .story-cover-illustration-image").click()
  
