# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTest():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_test(self):
    # Test name: test
    # Step # | name | target | value | comment
    # 1 | open | https://stories.duolingo.com/lessons/fr-bonjour |  | 
    self.driver.get("https://stories.duolingo.com/lessons/fr-bonjour")
    # 2 | setWindowSize | 1280x773 |  | 
    self.driver.set_window_size(1280, 773)
    # 3 | mouseDownAt | css=.phrase:nth-child(6) .point-to-phrase-synced-text | 32.171875,14 | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".phrase:nth-child(6) .point-to-phrase-synced-text")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    # 4 | mouseMoveAt | css=.phrase:nth-child(6) .point-to-phrase-synced-text | 32.171875,14 | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".phrase:nth-child(6) .point-to-phrase-synced-text")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 5 | mouseUpAt | css=.phrase:nth-child(6) .point-to-phrase-synced-text | 32.171875,14 | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".phrase:nth-child(6) .point-to-phrase-synced-text")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    # 6 | click | css=.phrase:nth-child(6) .point-to-phrase-synced-text |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".phrase:nth-child(6) .point-to-phrase-synced-text").click()
  
