# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTest():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_test(self):
    # Test name: test
    # Step # | name | target | value | comment
    # 1 | open | https://stories.duolingo.com/?referrer=web_tab |  | 
    self.driver.get("https://stories.duolingo.com/?referrer=web_tab")
    # 2 | setWindowSize | 1280x773 |  | 
    self.driver.set_window_size(1280, 773)
    # 3 | click | css=.set:nth-child(2) > .story:nth-child(3) .story-cover-illustration-image |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".set:nth-child(2) > .story:nth-child(3) .story-cover-illustration-image").click()
    # 4 | mouseDownAt | css=.continue | 67,15.5 | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".continue")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    # 5 | mouseMoveAt | css=.continue | 67,15.5 | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".continue")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 6 | mouseUpAt | css=.continue | 67,15.5 | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".continue")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    # 7 | click | css=.continue |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".continue").click()
    # 8 | click | css=.continue |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".continue").click()
    # 9 | mouseOver | css=.continue |  | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".continue")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 10 | mouseDownAt | css=.click-to-select:nth-child(1) > button | 19,20 | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".click-to-select:nth-child(1) > button")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    # 11 | mouseMoveAt | css=.click-to-select:nth-child(1) > button | 19,20 | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".click-to-select:nth-child(1) > button")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 12 | mouseUpAt | css=.click-to-select:nth-child(1) > button | 19,20 | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".click-to-select:nth-child(1) > button")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    # 13 | click | css=.click-to-select:nth-child(1) > button |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".click-to-select:nth-child(1) > button").click()
  
