# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTest():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_test(self):
    # Test name: test
    # Step # | name | target | value | comment
    # 1 | open | https://stories.duolingo.com/lessons/fr-bonjour |  | 
    self.driver.get("https://stories.duolingo.com/lessons/fr-bonjour")
    # 2 | setWindowSize | 1280x773 |  | 
    self.driver.set_window_size(1280, 773)
    # 3 | mouseDownAt | css=li:nth-child(5) > .selectable-token | 31.078125,23 | 
    element = self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(5) > .selectable-token")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    # 4 | mouseMoveAt | css=li:nth-child(5) > .selectable-token | 31.078125,23 | 
    element = self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(5) > .selectable-token")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 5 | mouseUpAt | css=li:nth-child(5) > .selectable-token | 31.078125,23 | 
    element = self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(5) > .selectable-token")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    # 6 | click | css=li:nth-child(5) > .selectable-token |  | 
    self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(5) > .selectable-token").click()
    # 7 | mouseDownAt | css=li:nth-child(10) > .selectable-token | 25.421875,28 | 
    element = self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(10) > .selectable-token")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    # 8 | mouseMoveAt | css=li:nth-child(10) > .selectable-token | 25.421875,28 | 
    element = self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(10) > .selectable-token")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 9 | mouseUpAt | css=li:nth-child(10) > .selectable-token | 25.421875,28 | 
    element = self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(10) > .selectable-token")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    # 10 | click | css=li:nth-child(10) > .selectable-token |  | 
    self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(10) > .selectable-token").click()
    # 11 | mouseOver | css=li:nth-child(10) > .selectable-token |  | 
    element = self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(10) > .selectable-token")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 12 | mouseOut | css=li:nth-child(10) > .selectable-token |  | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
  
